title: Favian Sulthan Wafi
logo:  ![foto diri](https://github.com/FavianSulthanW/FavianSulthanW.github.io/assets/153904968/bf1aef3a-d640-4325-92dc-124b13ec9dd3)
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
