title: Favian Sulthan Wafi
logo: ![foto diri](https://github.com/FavianSulthanW/FavianSulthanW.github.io/assets/153904968/2588dc9c-c049-4d73-bf56-e08e3bd3237e)
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
